keys:
  - &hosts:
    - &antares age1dy73s85fpp3wsj6larug52wrf838ltpux7zv0k9hnmkjww5l5upqj25j5y
    - &sargas age1k2v6delpxnc5zwg4uvp5zd96j4sxwq8y45av2nkyty80fx4r9gnqcp8w78
creation_rules:
  - key_groups:
    - age:
      - *antares
      - *sargas
