keys:
  - &hosts:
    - &antares age1nnedvxpqyqkrhezz299qsw9kezxu7n6rz3kzpwz3hkfrvy63muqqvp0c29
    - &sargas age12nu8et3l2ay9xclphgmstq97tf9j0u04psef9f8u74h7pntnce3qzpjj8q
creation_rules:
  - key_groups:
    - age:
      - *antares
      - *sargas
