keys:
  - &hosts:
    - &antares age1nnedvxpqyqkrhezz299qsw9kezxu7n6rz3kzpwz3hkfrvy63muqqvp0c29
    - &sargas age1k2v6delpxnc5zwg4uvp5zd96j4sxwq8y45av2nkyty80fx4r9gnqcp8w78
creation_rules:
  - key_groups:
    - age:
      - *antares
      - *sargas
