name: "Push to homeserver"

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan vm-debian >> ~/.ssh/known_hosts
  
      - name: SSH and run commands
        run: |
          ssh -o StrictHostKeyChecking=no c3r5b8@vm-debian <<'EOF'
            cd server
            ./update.sh pull
          EOF
